// Generated by CoffeeScript 1.9.3
(function() {
  var Slider;

  Slider = React.createClass({displayName: "Slider",
    interval_handler: null,
    getInitialState: function() {
      return {
        image_index: 0
      };
    },
    componentDidMount: function() {
      return this.start();
    },
    showNextImage: function() {
      var new_index;
      new_index = this.state.image_index !== this.props.images.length - 1 ? this.state.image_index + 1 : 0;
      return this.setState({
        image_index: new_index
      });
    },
    showPrevImage: function() {
      var new_index;
      new_index = this.state.image_index === this.props.images.length - 1 ? this.state.image_index + 1 : 0;
      return this.setState({
        image_index: new_index
      });
    },
    start: function() {
      return this.interval_handler = setInterval(this.showNextImage, this.props.interval);
    },
    pause: function() {
      return clearInterval(this.interval_handler);
    },
    render: function() {
      return React.createElement("div", {
        "id": "slider",
        "style": {
          backgroundImage: 'url(' + this.props.images[this.state.image_index] + ')'
        },
        "onMouseOver": this.pause,
        "onMouseOut": this.start
      }, React.createElement("button", {
        "onClick": this.showNextImage
      }, "\x3E"), React.createElement("button", {
        "onClick": this.showPrevImage
      }, "\x3C"));
    }
  });

  document.addEventListener('DOMContentLoaded', function() {
    return React.render(React.createElement(Slider, {
      "images": ['imgs/1.jpg', 'imgs/2.jpg', 'imgs/3.jpg'],
      "interval": 2000.
    }), document.getElementById('app-container'));
  });

}).call(this);
